spring.application.name=verzel-events

# Configuração do Banco de Dados (Suporta Nuvem e Docker Local)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/eventos_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Secrets e Chaves
app.jwt.secret=${JWT_SECRET:3TPvHykXewlb3ZUvnLygwBUAHodapBMVU2xeG3kc2lM=}
app.jwt.expiration=86400000

app.tmdb.api-key=${TMDB_API_KEY:eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIyM2RiNWNhOWMwMTE1NDcyMTE2NzdiMzBiMmExZTM3ZSIsIm5iZiI6MTc4NjkyNzU2NS4zMjYwMDAyLCJzdWIiOiI2YTgyNTljZGVmMDQwMGEwODc0OTU5YTYiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.RDpyUNbON0YWWmbwjkfhpSju0g2mBNtVK20JKWfPXzA}

app.qr.secret=${QR_SECRET:OOO2QTrfHfSFemeJYUjZ5Hj+GDySjiw/dynwpK0XbMk=}