spring.datasource.url=jdbc:postgresql://localhost:5432/eventos_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.jwt.secret=SUA_CHAVE_AQUI_GERE_COM_KEYS_SECRETKEYFOR
app.jwt.expiration=86400000

app.tmdb.api-key=SEU_TOKEN_AQUI
app.qr.secret=SUA_CHAVE_QR_AQUI